insert into score (id, isOG, scoring_time, player_id, match_id) values (1, false, 23, 4, 1);
insert into score (id, isOG, scoring_time, player_id, match_id) values (2, false, 3, 1, 1);
insert into score (id, isOG, scoring_time, player_id, match_id) values (3, false, 23, 49, 1);
insert into score (id, isOG, scoring_time, player_id, match_id) values (4, true, 33, 41, 2);
insert into score (id, isOG, scoring_time, player_id, match_id) values (5, false, 83, 49, 2);
insert into score (id, isOG, scoring_time, player_id, match_id) values (6, false, 63, 10, 2);
insert into score (id, isOG, scoring_time, player_id, match_id) values (7, false, 32, 10, 2);
insert into score (id, isOG, scoring_time, player_id, match_id) values (8, false, 32, 20, 4);
insert into score (id, isOG, scoring_time, player_id, match_id) values (9, false, 12, 20, 4);
insert into score (id, isOG, scoring_time, player_id, match_id) values (10, true, 3, 20, 4);
insert into score (id, isOG, scoring_time, player_id, match_id) values (11, false, 82, 20, 4);
insert into score (id, isOG, scoring_time, player_id, match_id) values (12, false, 2, 22, 5);
insert into score (id, isOG, scoring_time, player_id, match_id) values (13, false, 5, 24, 5);
insert into score (id, isOG, scoring_time, player_id, match_id) values (14, false, 7, 22, 5);
insert into score (id, isOG, scoring_time, player_id, match_id) values (15, false, 87, 29, 5);
insert into score (id, isOG, scoring_time, player_id, match_id) values (16, true, 89, 26, 5);
insert into score (id, isOG, scoring_time, player_id, match_id) values (17, false, 79, 27, 5);
insert into score (id, isOG, scoring_time, player_id, match_id) values (18, false, 83, 27, 5);
insert into score (id, isOG, scoring_time, player_id, match_id) values (19, false, 85, 26, 5);

alter sequence score_id_seq restart with 20;