insert into team(id,name) values (1,'Fc Bayern');
insert into team(id,name) values (2,'Fc Barcelona');
insert into team(id,name) values (3,'Rb Leipzig');
insert into team(id,name) values (4,'As Monaco');
insert into team(id,name) values (5,'Fc Real de Madrid');
insert into team(id,name) values (6,'Fc Liverpool');
insert into team(id,name) values (7,'Manchester City');
insert into team(id,name) values (8,'Manchester United');
insert into team(id,name) values (9,'Atletico de Madrid');
insert into team(id,name) values (10,'Juventus');